/**
 * Android "Share to Memory Map" overlay.
 *
 * Adds a second, translucent activity that is the app's share target for
 * text/links. It renders the `shareOverlay` React root (src/share/
 * ShareOverlayRoot.tsx) on top of whatever app shared the link - Instagram
 * stays visible behind it - and finishing it drops the user straight back
 * where they were. It runs in its own task (taskAffinity=""), so it never
 * brings the main app's screens forward.
 */
const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withAndroidStyles, withDangerousMod } = require('expo/config-plugins');

const ACTIVITY = 'ShareOverlayActivity';
const THEME = 'Theme.App.ShareOverlay';

function activityKotlin(packageName) {
  return `package ${packageName}

import android.content.Intent
import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

/**
 * Generated by plugins/withAndroidShareOverlay.js - edit that file instead.
 * Translucent share target that hosts the "shareOverlay" React root.
 */
class ${ACTIVITY} : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    // Like MainActivity: don't restore view state across process death.
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "shareOverlay"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {
      override fun getLaunchOptions(): Bundle =
        Bundle().apply { putString("text", sharedText(this@${ACTIVITY}.intent)) }
    }

  private fun sharedText(intent: Intent?): String {
    if (intent?.action != Intent.ACTION_SEND) return ""
    return listOfNotNull(
      intent.getStringExtra(Intent.EXTRA_TEXT),
      intent.getStringExtra(Intent.EXTRA_SUBJECT),
    ).joinToString(" ")
  }
}
`;
}

const withOverlayActivityFile = (config) =>
  withDangerousMod(config, [
    'android',
    async (config) => {
      const packageName = config.android?.package;
      if (!packageName) throw new Error('withAndroidShareOverlay: android.package is required');
      const dir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/java', ...packageName.split('.'));
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${ACTIVITY}.kt`), activityKotlin(packageName));
      return config;
    },
  ]);

const withOverlayTheme = (config) =>
  withAndroidStyles(config, (config) => {
    const styles = config.modResults.resources;
    styles.style = (styles.style ?? []).filter((style) => style.$.name !== THEME);
    const item = (name, value) => ({ $: { name }, _: value });
    styles.style.push({
      $: { name: THEME, parent: 'Theme.AppCompat.DayNight.NoActionBar' },
      item: [
        item('android:windowIsTranslucent', 'true'),
        item('android:windowBackground', '@android:color/transparent'),
        item('android:windowNoTitle', 'true'),
        item('android:backgroundDimEnabled', 'false'),
        item('android:windowContentOverlay', '@null'),
        item('android:statusBarColor', '@android:color/transparent'),
        item('android:navigationBarColor', '@android:color/transparent'),
        item('android:windowAnimationStyle', '@android:style/Animation.Translucent'),
      ],
    });
    return config;
  });

const withOverlayManifest = (config) =>
  withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application?.[0];
    if (!application) return config;
    application.activity = (application.activity ?? []).filter((activity) => activity.$['android:name'] !== `.${ACTIVITY}`);
    application.activity.push({
      $: {
        'android:name': `.${ACTIVITY}`,
        'android:theme': `@style/${THEME}`,
        'android:exported': 'true',
        // Own task, so Instagram (not our main screen) shows behind it, and
        // no separate entry in Recents.
        'android:taskAffinity': '',
        'android:excludeFromRecents': 'true',
        'android:noHistory': 'true',
        'android:screenOrientation': 'portrait',
        'android:windowSoftInputMode': 'adjustResize',
        'android:configChanges': 'keyboard|keyboardHidden|orientation|screenSize|screenLayout|uiMode|smallestScreenSize',
      },
      'intent-filter': [
        {
          action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          data: [{ $: { 'android:mimeType': 'text/plain' } }],
        },
      ],
    });
    return config;
  });

module.exports = (config) => withOverlayManifest(withOverlayTheme(withOverlayActivityFile(config)));
